version: "3"
services:
  web:
    image: weirdwater/showrunner:latest
    ports:
      - "80:3000"
    environment:
      - HOST_DOMAIN=188.226.145.184
      - PORT=80
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
    links:
      - mongo
    networks:
      - webnet
  mongo:
    image: mongo:3.4
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    networks:
      - webnet
networks:
  webnet:
